name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Login no Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build da imagem
      run: docker build -t alex282874/app_build_cont:latest .

    - name: Push para o Docker Hub
      run: docker push alex282874/app_build_cont:latest

    - name: Configura kubectl
      uses: azure/setup-kubectl@v3

    - name: Acessar o cluster AKS
      uses: azure/aks-set-context@v3
      with:
        resource-group: aks_lab_estudos
        cluster-name: aks_devops

    - name: Aplicar manifestos no Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
